### ISSUE TITLE
TypeAlias and "|" for unions are python 3.10+ features

### ISSUE THREAD

**Issue by timcera** [hyriver/pygeoogc#57]
### What happened?

Forked the development version to prepare a pull request and noticed that in "cache_keys.py" you started using TypeAlias and "|" for unions.  I was caught recently taking the advice of a linter, I think pyright that was targeting the very latest python versions but I wanted to support python 3.8+.  I noticed that pygeoogc also supports 3.8+ and just wanted to point out the TypeAlias and "|" for unions are 3.10+ features.

Kind regards,
Tim

### MVCE confirmation

- [ ] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue.
- [ ] Complete example — the example is self-contained, including all data and the text of any traceback.
- [ ] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Environment

<details>

git fork 

</details>

**Comment by cheginit** [comment]
Tim, thanks for opening the issue, I will fix it soon.
