### ISSUE TITLE
WFS request does not work

### ISSUE THREAD

**Issue by Magic-IP** [hyriver/pygeoogc#68]
### What happened?

I use the code below but it returns error (shown in example section). I tried everything I knew but unable to get a result.

bounds[0] = (-78.37650499999897, 40.691622000000514, -77.1441599999993, 41.252665000000405)

wfs = WFS(
    ServiceURL().wfs.fema,
    layer="NFHL:Base_Flood_Elevations",
    outformat="geojson",
    crs=4326,)
r = wfs.getfeature_bybox(bounds[0], box_crs=4326)

flood = geoutils.json2geodf(r.json(), 4326, 4326)

### What did you expect to happen?

to get the map for flood area

### Minimal Complete Verifiable Example

```Python
ValueError                                Traceback (most recent call last)
File ~\Anaconda3_5\envs\pvlibdev\lib\site-packages\pygeoogc\pygeoogc.py:589, in WFS.getfeature_bybox(self, bbox, box_crs, always_xy, sort_attr)
    588 try:
--> 589     nfeatures = int(resp[0].split(self.nfeat_key)[-1].split(" ")[0].strip('"'))
    590 except (IndexError, ValueError) as ex:

ValueError: invalid literal for int() with base 10: '<?xml'

The above exception was the direct cause of the following exception:

ServiceError                              Traceback (most recent call last)
Cell In[40], line 6
      1 wfs = WFS(
      2     ServiceURL().wfs.fema,
      3     layer="NFHL:Base_Flood_Elevations",
      4     outformat="geojson",
      5     crs=4269,)
----> 6 r = wfs.getfeature_bybox(bounds[0], box_crs=4326)
      7 # r = wfs.getfeature_bygeom(bounds_pgon, geo_crs=4326)
      8 flood = geoutils.json2geodf(r.json(), 4326, 4326)

File ~\Anaconda3_5\envs\pvlibdev\lib\site-packages\pygeoogc\pygeoogc.py:591, in WFS.getfeature_bybox(self, bbox, box_crs, always_xy, sort_attr)
    589     nfeatures = int(resp[0].split(self.nfeat_key)[-1].split(" ")[0].strip('"'))
    590 except (IndexError, ValueError) as ex:
--> 591     raise ServiceError(resp[0], self.url) from ex
    593 payloads = [
    594     {
    595         "service": "wfs",
   (...)
    604     for i in range(0, nfeatures, self.max_nrecords)
    605 ]
    607 return self.retrieve([self.url] * len(payloads), [{"params": p} for p in payloads])

ServiceError: Service returned the following error message:
URL: https://hazards.fema.gov/gis/nfhl/services/public/NFHL/MapServer/WFSServer
ERROR: <?xml version="1.0" encoding="utf-8" ?><wfs:FeatureCollection xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:NFHL="https://hazards.fema.gov/arcgis/admin/services/NFHL/MapServer/WFSServer" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wfs http://schemas.opengis.net/wfs/1.0.0/WFS-basic.xsd http://www.opengis.net/gml http://schemas.opengis.net/gml/2.1.2/feature.xsd https://hazards.fema.gov/arcgis/admin/services/NFHL/MapServer/WFSServer https://hazards.fema.gov/nfhl/services/public/NFHL/MapServer/WFSServer?service=wfs%26version=1.0.0%26request=DescribeFeatureType"><gml:boundedBy><gml:Box srsName="EPSG:4269"><gml:coordinates>0.00000000,0.00000000 0.00000000,0.00000000</gml:coordinates>  </gml:Box></gml:boundedBy></wfs:FeatureCollection>
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Relevant log output

```Python
ValueError                                Traceback (most recent call last)
File ~\Anaconda3_5\envs\pvlibdev\lib\site-packages\pygeoogc\pygeoogc.py:589, in WFS.getfeature_bybox(self, bbox, box_crs, always_xy, sort_attr)
    588 try:
--> 589     nfeatures = int(resp[0].split(self.nfeat_key)[-1].split(" ")[0].strip('"'))
    590 except (IndexError, ValueError) as ex:

ValueError: invalid literal for int() with base 10: '<?xml'

The above exception was the direct cause of the following exception:

ServiceError                              Traceback (most recent call last)
Cell In[40], line 6
      1 wfs = WFS(
      2     ServiceURL().wfs.fema,
      3     layer="NFHL:Base_Flood_Elevations",
      4     outformat="geojson",
      5     crs=4269,)
----> 6 r = wfs.getfeature_bybox(bounds[0], box_crs=4326)
      7 # r = wfs.getfeature_bygeom(bounds_pgon, geo_crs=4326)
      8 flood = geoutils.json2geodf(r.json(), 4326, 4326)

File ~\Anaconda3_5\envs\pvlibdev\lib\site-packages\pygeoogc\pygeoogc.py:591, in WFS.getfeature_bybox(self, bbox, box_crs, always_xy, sort_attr)
    589     nfeatures = int(resp[0].split(self.nfeat_key)[-1].split(" ")[0].strip('"'))
    590 except (IndexError, ValueError) as ex:
--> 591     raise ServiceError(resp[0], self.url) from ex
    593 payloads = [
    594     {
    595         "service": "wfs",
   (...)
    604     for i in range(0, nfeatures, self.max_nrecords)
    605 ]
    607 return self.retrieve([self.url] * len(payloads), [{"params": p} for p in payloads])

ServiceError: Service returned the following error message:
URL: https://hazards.fema.gov/gis/nfhl/services/public/NFHL/MapServer/WFSServer
ERROR: <?xml version="1.0" encoding="utf-8" ?><wfs:FeatureCollection xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:NFHL="https://hazards.fema.gov/arcgis/admin/services/NFHL/MapServer/WFSServer" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wfs http://schemas.opengis.net/wfs/1.0.0/WFS-basic.xsd http://www.opengis.net/gml http://schemas.opengis.net/gml/2.1.2/feature.xsd https://hazards.fema.gov/arcgis/admin/services/NFHL/MapServer/WFSServer https://hazards.fema.gov/nfhl/services/public/NFHL/MapServer/WFSServer?service=wfs%26version=1.0.0%26request=DescribeFeatureType"><gml:boundedBy><gml:Box srsName="EPSG:4269"><gml:coordinates>0.00000000,0.00000000 0.00000000,0.00000000</gml:coordinates>  </gml:Box></gml:boundedBy></wfs:FeatureCollection>
```

### Anything else we need to know?

**Two things:**

**First in another account,** it seems the     fws: str = (
        "https://www.fws.gov/wetlandsmapservice/services/Wetlands_Raster/ImageServer/WMSServer"

is changed to 'https://www.fws.gov/wetlandsmapservice/services/WetlandsRaster/ImageServer/WMSServer'.

**Second back to the issue:** 

I tried some debugging to see the response from the server and here is the result

ipdb> resp
['<?xml version="1.0" encoding="utf-8" ?><wfs:FeatureCollection xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:NFHL="https://hazards.fema.gov/arcgis/admin/services/NFHL/MapServer/WFSServer" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wfs http://schemas.opengis.net/wfs/1.0.0/WFS-basic.xsd http://www.opengis.net/gml http://schemas.opengis.net/gml/2.1.2/feature.xsd https://hazards.fema.gov/arcgis/admin/services/NFHL/MapServer/WFSServer [https://hazards.fema.gov/nfhl/services/public/NFHL/MapServer/WFSServer?service=wfs%26version=1.0.0%26request=DescribeFeatureType"><gml:boundedBy><gml:Box](https://hazards.fema.gov/nfhl/services/public/NFHL/MapServer/WFSServer?service=wfs%26version=1.0.0%26request=DescribeFeatureType%22%3E%3Cgml:boundedBy%3E%3Cgml:Box) srsName="EPSG:4269"><gml:coordinates>0.00000000,0.00000000 0.00000000,0.00000000</gml:coordinates>  </gml:Box></gml:boundedBy></wfs:FeatureCollection>']
ipdb> c

### Environment

<details>
SYS INFO
--------
commit: None
python: 3.10.9 | packaged by conda-forge | (main, Jan 11 2023, 15:15:40) [MSC v.1916 64 bit (AMD64)]
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: ('English_United States', '1252')

PACKAGE                VERSION
-------------------------------
async-retriever        0.16.0
pygeoogc               0.16.3
pygeoutils             0.16.3
py3dep                 0.16.3
pynhd                  0.16.2
pygridmet              N/A
pydaymet               N/A
hydrosignatures        0.16.0
pynldas2               N/A
pygeohydro             0.16.5
aiohttp                3.9.3
aiohttp-client-cache   0.11.0
aiosqlite              0.20.0
cytoolz                0.12.3
ujson                  5.10.0
defusedxml             0.7.1
joblib                 1.3.2
multidict              6.0.5
owslib                 0.30.0
pyproj                 3.6.1
requests               2.32.3
requests-cache         1.2.1
shapely                2.0.4
url-normalize          1.4.3
urllib3                1.26.14
yarl                   1.9.4
geopandas              1.0.0
netcdf4                1.6.0
numpy                  1.23.5
rasterio               1.3.10
rioxarray              0.15.6
scipy                  1.13.1
xarray                 2024.6.0
click                  8.1.7
pyflwdir               N/A
networkx               3.1
pyarrow                15.0.2
folium                 0.17.0
h5netcdf               1.3.0
matplotlib             3.9.0
pandas                 2.2.2
numba                  0.56.4
bottleneck             1.4.0
py7zr                  N/A
pyogrio                0.9.0
-------------------------------

</details>

**Comment by cheginit** [comment]
For accessing NFHL data, you can directly use PyGeoHydro:

```python
from pygeohydro import NFHL

nfhl = NFHL("NFHL", "base flood elevations")
bounds = (-78.37650499999897, 40.691622000000514, -77.1441599999993, 41.252665000000405)
data = nfhl.bygeom(bounds)
```

You can check the documentation of the class [here](https://docs.hyriver.io/autoapi/pygeohydro/nfhl/index.html)

**Comment by Magic-IP** [comment]
It works. Thanks
